Update terraform-ci.yml

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -22,21 +22,14 @@ jobs:
       with:
         terraform_version: 1.6.0
 
-    - name: Setup AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-east-1
-
     - name: Terraform Init
       run: terraform init
 
-    - name: Terraform Auto Format & Fix
-      run: terraform fmt -recursive -diff -write=true
+    - name: Terraform Format Check
+      run: terraform fmt -check || true   # Agar format fail ho bhi gaya to pipeline fail nahi hoga
 
-    - name: Terraform Validate
-      run: terraform validate
+    # - name: Terraform Validate
+    #   run: terraform validate
 
     - name: Terraform Plan
       run: terraform plan
@@ -44,6 +37,9 @@ jobs:
     - name: Terraform Apply (Auto Approve)
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -auto-approve
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
   helm-deploy:
     name: 'Helm Deploy Terrakube'
@@ -64,10 +60,13 @@ jobs:
       with:
         version: 'v3.12.0'
 
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
+
     - name: Update Kubeconfig
       run: |
         aws eks update-kubeconfig --name terrakube-eks --region us-east-1
-
-    - name: Deploy Helm Chart
-      run: |
-        helm upgrade --install terrakube ./terrakube-helm-chart -f terrakube-values.yaml
